apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
  labels:
    app: spring-boot
spec:
    replicas: 1
    selector:
      matchLabels:
        app: spring-boot
    template:
      metadata:
        labels:
          app: spring-boot
      spec:
        containers:
          - name: spring-boot
            image: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot:latest
            ports:
              - containerPort: 8080