# Complete the service kubernetes file for this project

# Path: service.yml

apiVersion: v1
kind: Service
metadata:
  name: spring-boot
spec:
    type: NodePort
    ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30000
    selector:
        app: spring-boot