---
name: Build and Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  run-checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUBB_TOKEN }}
          reporter: github-check
          level: info
          checkstyle_config: google_checks.xml
          workdir: ./src/main/java

  run-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBB_TOKEN }}
          FILTER_REGEX_EXCLUDE: ".*mvn*|.*src*|.*github*"
          IGNORE_GITIGNORED_FILES: true

  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [run-lint, run-checkstyle]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run: |
          mvn clean 
          mvn -B package --file pom.xml

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot:latesttag

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/spring-boot:latesttag

      - name: Start Minikube
        uses: medyagh/setup-minikube@master

      - name: Test Minikube
        run: kubectl get pods -A

      - name: Deploy to Minikube
        run: kubectl apply -f deployment.yml

      - name: Start Service
        run: kubectl apply -f service.yml

      - name: Test service
        run: minikube service list